CREATE TABLE PLAYERS(
PLAYER_NAME VARCHAR(20) PRIMARY KEY,
CATEGORY VARCHAR(20)
);

CREATE TABLE TEAM(
TEAM_NAME VARCHAR(10),
SCORE INTEGER,
PLAYER_NAME VARCHAR(20),
FOREIGN KEY(PLAYER_NAME) REFERENCES PLAYERS(PLAYER_NAME),
PRIMARY KEY(TEAM_NAME, PLAYER_NAME)
);

CREATE TABLE USERS(
USER_ID INTEGER AUTO_INCREMENT,
EMAIL_ID VARCHAR(30),
PASSWORD VARCHAR(20),
USERNAME VARCHAR(20),
TEAM_NAME VARCHAR(10),
PRIMARY KEY(USER_ID, EMAIL_ID),
FOREIGN KEY(TEAM_NAME) REFERENCES TEAM(TEAM_NAME) ON DELETE CASCADE
);

CREATE TABLE INDIVIDUAL_SCORE(
SID INTEGER PRIMARY KEY AUTO_INCREMENT,
PLAYER_NAME VARCHAR(20),
FOREIGN KEY(PLAYER_NAME) REFERENCES PLAYERS(PLAYER_NAME) ON DELETE CASCADE,
RUNS INTEGER,
FACED INTEGER,
FOURS INTEGER,
SIXES INTEGER,
BOWLED INTEGER,
GIVEN INTEGER,
WICKETS INTEGER
);

CREATE TABLE MATCHES(
MATCH_ID INTEGER PRIMARY KEY AUTO_INCREMENT
);

INSERT INTO PLAYERS VALUE('Virat Kohli', 'batsmen');
INSERT INTO PLAYERS VALUE('Aaron Finch', 'batsmen');
INSERT INTO PLAYERS VALUE('Ab De-Villiers', 'wicketkeeper');
INSERT INTO PLAYERS VALUE('Yuzvender Chahal', 'bowler');
INSERT INTO PLAYERS VALUE('Chris Morris', 'allrounder');
INSERT INTO PLAYERS VALUE('Devdutt Padikkal', 'batsmen');
INSERT INTO PLAYERS VALUE('Gurkeerat Singh', 'batsmen');
INSERT INTO PLAYERS VALUE('Moeen Ali', 'allrounder');
INSERT INTO PLAYERS VALUE('Saini', 'bowler');
INSERT INTO PLAYERS VALUE('Shivam Dube', 'allrounder');
INSERT INTO PLAYERS VALUE('Sundar', 'allrounder');
INSERT INTO PLAYERS VALUE('Dhoni', 'batsmen');
INSERT INTO PLAYERS VALUE('Ambati Rayudu', 'batsmen');
INSERT INTO PLAYERS VALUE('Chahar', 'bowler');
INSERT INTO PLAYERS VALUE('Dwayne Bravo', 'allrounder');
INSERT INTO PLAYERS VALUE('Du Plessis', 'allrounder');
INSERT INTO PLAYERS VALUE('Imaran Tahir', 'bowler');
INSERT INTO PLAYERS VALUE('Jadeja', 'allrounder');
INSERT INTO PLAYERS VALUE('Murali Vijay', 'batsmen');
INSERT INTO PLAYERS VALUE('Narayan Jagdeeshan', 'wicketkeeper');
INSERT INTO PLAYERS VALUE('Shane Watson', 'allrounder');
INSERT INTO PLAYERS VALUE('Shardul Thakur', 'bowler');

UPDATE INDIVIDUAL_SCORE SET RUNS = 15 WHERE PLAYER_NAME = 'Aaron Finch';

INSERT INTO INDIVIDUAL_SCORE(PLAYER_NAME, RUNS, FACED, FOURS, SIXES, BOWLED, GIVEN, WICKETS)
 VALUES('Virat Kohli', 50, 43, 1, 1, 0, 0, 0);
INSERT INTO INDIVIDUAL_SCORE(PLAYER_NAME, RUNS, FACED, FOURS, SIXES, BOWLED, GIVEN, WICKETS)
 VALUES('Aaron Finch', 15, 11, 3, 0, 0, 0, 0);
INSERT INTO INDIVIDUAL_SCORE(PLAYER_NAME, RUNS, FACED, FOURS, SIXES, BOWLED, GIVEN, WICKETS)
 VALUES('Ab De-Villiers', 39, 36, 4, 0, 0, 0, 0);
INSERT INTO INDIVIDUAL_SCORE(PLAYER_NAME, RUNS, FACED, FOURS, SIXES, BOWLED, GIVEN, WICKETS)
 VALUES('Yuzvender Chahal', 0, 0, 0, 0, 24, 21, 1);
INSERT INTO INDIVIDUAL_SCORE(PLAYER_NAME, RUNS, FACED, FOURS, SIXES, BOWLED, GIVEN, WICKETS)
 VALUES('Chris Morris', 2, 5, 0, 0, 22, 36, 1);
INSERT INTO INDIVIDUAL_SCORE(PLAYER_NAME, RUNS, FACED, FOURS, SIXES, BOWLED, GIVEN, WICKETS)
 VALUES('Devdutt Padikkal', 22, 21, 2, 1, 0, 0, 0);
INSERT INTO INDIVIDUAL_SCORE(PLAYER_NAME, RUNS, FACED, FOURS, SIXES, BOWLED, GIVEN, WICKETS)
 VALUES('Gurkeerat Singh', 2, 2, 0, 0, 0, 0, 0);
INSERT INTO INDIVIDUAL_SCORE(PLAYER_NAME, RUNS, FACED, FOURS, SIXES, BOWLED, GIVEN, WICKETS)
 VALUES('Moeen Ali', 1, 2, 0, 0, 12, 17, 0);
INSERT INTO INDIVIDUAL_SCORE(PLAYER_NAME, RUNS, FACED, FOURS, SIXES, BOWLED, GIVEN, WICKETS)
 VALUES('Saini', 0, 0, 0, 0, 18, 19, 0);
INSERT INTO INDIVIDUAL_SCORE(PLAYER_NAME, RUNS, FACED, FOURS, SIXES, BOWLED, GIVEN, WICKETS)
 VALUES('Shivam Dube', 5, 2, 1, 0, 12, 29, 0);
INSERT INTO INDIVIDUAL_SCORE(PLAYER_NAME, RUNS, FACED, FOURS, SIXES, BOWLED, GIVEN, WICKETS)
 VALUES('Sundar', 5, 2, 1, 0, 24, 27, 0);
INSERT INTO INDIVIDUAL_SCORE(PLAYER_NAME, RUNS, FACED, FOURS, SIXES, BOWLED, GIVEN, WICKETS)
 VALUES('Dhoni', 19, 21, 3, 0, 0, 0, 0);
INSERT INTO INDIVIDUAL_SCORE(PLAYER_NAME, RUNS, FACED, FOURS, SIXES, BOWLED, GIVEN, WICKETS)
 VALUES('Ambati Rayudu', 39, 27, 3, 2, 0, 0, 0);
INSERT INTO INDIVIDUAL_SCORE(PLAYER_NAME, RUNS, FACED, FOURS, SIXES, BOWLED, GIVEN, WICKETS)
 VALUES('Chahar', 0, 0, 0, 0, 24, 31, 2);
INSERT INTO INDIVIDUAL_SCORE(PLAYER_NAME, RUNS, FACED, FOURS, SIXES, BOWLED, GIVEN, WICKETS)
 VALUES('Dwayne Bravo', 65, 51, 4, 3, 12, 20, 0);
INSERT INTO INDIVIDUAL_SCORE(PLAYER_NAME, RUNS, FACED, FOURS, SIXES, BOWLED, GIVEN, WICKETS)
 VALUES('Du Plessis', 25, 13, 2, 2, 0, 0, 0);
INSERT INTO INDIVIDUAL_SCORE(PLAYER_NAME, RUNS, FACED, FOURS, SIXES, BOWLED, GIVEN, WICKETS)
 VALUES('Imaran Tahir', 0, 0, 0, 0, 24, 30, 0);
INSERT INTO INDIVIDUAL_SCORE(PLAYER_NAME, RUNS, FACED, FOURS, SIXES, BOWLED, GIVEN, WICKETS)
 VALUES('Jadeja', 0, 0, 0, 0, 18, 20, 0);
INSERT INTO INDIVIDUAL_SCORE(PLAYER_NAME, RUNS, FACED, FOURS, SIXES, BOWLED, GIVEN, WICKETS)
 VALUES('Murali Vijay', 0, 0, 0, 0, 0, 0, 0);
INSERT INTO INDIVIDUAL_SCORE(PLAYER_NAME, RUNS, FACED, FOURS, SIXES, BOWLED, GIVEN, WICKETS)
 VALUES('Narayan Jagdeeshan', 0, 0, 0, 0, 0, 0, 0);
INSERT INTO INDIVIDUAL_SCORE(PLAYER_NAME, RUNS, FACED, FOURS, SIXES, BOWLED, GIVEN, WICKETS)
 VALUES('Shane Watson', 0, 0, 0, 0, 24, 23, 1);
INSERT INTO INDIVIDUAL_SCORE(PLAYER_NAME, RUNS, FACED, FOURS, SIXES, BOWLED, GIVEN, WICKETS)
 VALUES('Shardul Thakur', 0, 0, 0, 0, 18, 19, 3);

DELIMITER $$
CREATE PROCEDURE updateTeamScore(IN score INTEGER, IN teamName VARCHAR(10))
BEGIN
	UPDATE TEAM SET SCORE = score WHERE TEAM_NAME = teamName;
END$$
DELIMITER ;

CREATE TRIGGER set_score BEFORE INSERT ON TEAM
FOR EACH ROW UPDATE TEAM SET SCORE = 0;
DROP TRIGGER set_score;

 
DROP TABLE USERS;
DELETE FROM USERS;
DELETE FROM TEAM;
SELECT * FROM TEAM;
SELECT * FROM USERS;
SELECT * FROM INDIVIDUAL_SCORE;
